# authors:
# David Hernandez Lopez, david.hernandez@uclm.es
import os
import sys

current_path = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(current_path, '..'))

PHOTOGRAMMETRY_PROJECTS_DIALOG_TITLE = "Photogrammetry Projects"

CONST_NO_COMBO_SELECT = " ... "

FORMAT_PHOTOGRAMMETRY_TOOLS = 'Photogrammetry Tools'
FORMAT_PHOTOGRAMMETRY_TOOLS_FILE_EXTENSION = 'gpkg'
FORMAT_GEOMATIC_PRODUCTS = 'Geomatic Products'
FORMAT_GEOMATIC_PRODUCTS_FILE_EXTENSION = '' # no need a project file

extension_by_format = {}
extension_by_format[FORMAT_PHOTOGRAMMETRY_TOOLS] = FORMAT_PHOTOGRAMMETRY_TOOLS_FILE_EXTENSION
extension_by_format[FORMAT_GEOMATIC_PRODUCTS] = FORMAT_GEOMATIC_PRODUCTS_FILE_EXTENSION

FIELD_ID = "Id"
FIELD_ENABLED = "Enabled"
FIELD_DESCRIPTION = "Description"
FIELD_FILE = "File"
FIELD_ORTHOMOSAIC = "Orthomosaic"
FIELD_ORTHOMOSAIC_CRS = "Orthomosaic CRS"
FIELD_DSM = "DSM"
FIELD_DSM_CRS = "DSM CRS"
FIELD_DTM = "DTM"
FIELD_DTM_CRS = "DTM CRS"
FIELD_POINT_CLOUD = "Point Cloud"
FIELD_POINT_CLOUD_CRS = "Point Cloud CRS"
fields = [FIELD_ID, FIELD_ENABLED, FIELD_DESCRIPTION,
          FIELD_FILE, FIELD_ORTHOMOSAIC, FIELD_ORTHOMOSAIC_CRS,
          FIELD_DSM, FIELD_DSM_CRS, FIELD_DTM, FIELD_DTM_CRS,
          FIELD_POINT_CLOUD, FIELD_POINT_CLOUD_CRS]
HEADER_ID_TAG = FIELD_ID
HEADER_ENABLED_TAG = FIELD_ENABLED
HEADER_DESCRIPTION_TAG = FIELD_DESCRIPTION
HEADER_FILE_TAG = FIELD_FILE
HEADER_ORTHOMOSAIC_TAG = FIELD_ORTHOMOSAIC
HEADER_ORTHOMOSAIC_CRS_TAG = FIELD_ORTHOMOSAIC_CRS
HEADER_DSM_TAG = FIELD_DSM
HEADER_DSM_CRS_TAG = FIELD_DSM_CRS
HEADER_DTM_TAG = FIELD_DTM
HEADER_DTM_CRS_TAG = FIELD_DTM_CRS
HEADER_POINT_CLOUD_TAG = FIELD_POINT_CLOUD
HEADER_POINT_CLOUD_CRS_TAG = FIELD_POINT_CLOUD_CRS
headers = [HEADER_ID_TAG,
           HEADER_ENABLED_TAG,
           HEADER_DESCRIPTION_TAG,
           HEADER_FILE_TAG,
           HEADER_ORTHOMOSAIC_TAG,
           HEADER_ORTHOMOSAIC_CRS_TAG,
           HEADER_DSM_TAG,
           HEADER_DSM_CRS_TAG,
           HEADER_DTM_TAG,
           HEADER_DTM_CRS_TAG,
           HEADER_POINT_CLOUD_TAG,
           HEADER_POINT_CLOUD_CRS_TAG]
HEADER_ID_TOOLTIP = "Photogrammetry project identifier"
HEADER_ENABLE_TOOLTIP = "Enabled"
HEADER_DESCRIPTION_TOOLTIP = "Description"
HEADER_FILE_TOOLTIP = "File"
HEADER_ORTHOMOSAIC_TOOLTIP = "Orthomosaic file"
HEADER_ORTHOMOSAIC_CRS_TOOLTIP = "Orthomosaic file CRS"
HEADER_DSM_TOOLTIP = "Digital Surface Model file"
HEADER_DSM_CRS_TOOLTIP = "Digital Surface Model file CRS"
HEADER_DTM_TOOLTIP = "Digital Terrain Model file"
HEADER_DTM_CRS_TOOLTIP = "Digital Terrain Model file CRS"
HEADER_POINT_CLOUD_TOOLTIP = "Point Cloud file"
HEADER_POINT_CLOUD_CRS_TOOLTIP = "Point Cloud file CRS"
header_tooltips = [HEADER_ID_TOOLTIP,
                   HEADER_ENABLE_TOOLTIP,
                   HEADER_DESCRIPTION_TOOLTIP,
                   HEADER_FILE_TOOLTIP,
                   HEADER_ORTHOMOSAIC_TOOLTIP,
                   HEADER_ORTHOMOSAIC_CRS_TOOLTIP,
                   HEADER_DSM_TOOLTIP,
                   HEADER_DSM_CRS_TOOLTIP,
                   HEADER_DTM_TOOLTIP,
                   HEADER_DTM_CRS_TOOLTIP,
                   HEADER_POINT_CLOUD_TOOLTIP,
                   HEADER_POINT_CLOUD_CRS_TOOLTIP]

