# authors:
# David Hernandez Lopez, david.hernandez@uclm.es

from pyLibOpenCV import defs_opencv

GRAPHOS_DOCUMENT_TAG = "GraphosCameras"
GRAPHOS_AT_BLOCK_LABEL = "ATBlock"

GRAPHOS_XML_SENSORS_TAG = "Cameras"
GRAPHOS_XML_SENSOR_TAG = "Camera"
GRAPHOS_XML_SENSOR_ATTRIBUTE_ID = "@id"
GRAPHOS_XML_SENSOR_NO_MASTER_ID = -1
GRAPHOS_XML_SENSOR_MAKE_TAG = "Make"
GRAPHOS_XML_SENSOR_MODEL_TAG = "Model"
GRAPHOS_XML_SENSOR_SERIAL_NUMBER_TAG = "SerialNumber"
GRAPHOS_XML_SENSOR_TYPE_TAG = "Type"
GRAPHOS_XML_SENSOR_FOCAL_TAG = "Focal"
GRAPHOS_XML_SENSOR_WIDTH_TAG = "Width"
GRAPHOS_XML_SENSOR_HEIGHT_TAG = "Height"
GRAPHOS_XML_SENSOR_BITS_PER_PIXEL_TAG = "BitsPerPixel"
GRAPHOS_XML_SENSOR_SENSOR_SIZE_TAG = "SensorSize"
GRAPHOS_XML_SENSOR_BAND_NAME_TAG = "BandName"
GRAPHOS_XML_SENSOR_CALIBRATION_TAG = "Calibration"
GRAPHOS_XML_SENSOR_CALIBRATION_UNDISTORTED_TAG = "CalibrationUndistorted"

GRAPHOS_SENSOR_CALIBRATION_TYPE_OPENCV_1 = defs_opencv.OPENCV_CALIBRATION_TYPE_OPENCV_1
GRAPHOS_XML_SENSOR_CALIBRATION_FX_TAG = defs_opencv.OPENCV_CALIBRATION_FX_TAG
GRAPHOS_XML_SENSOR_CALIBRATION_FY_TAG = defs_opencv.OPENCV_CALIBRATION_FY_TAG
GRAPHOS_XML_SENSOR_CALIBRATION_CX_TAG = defs_opencv.OPENCV_CALIBRATION_CX_TAG
GRAPHOS_XML_SENSOR_CALIBRATION_CY_TAG = defs_opencv.OPENCV_CALIBRATION_CY_TAG
# GRAPHOS_XML_SENSOR_CALIBRATION_B1_TAG = "b1"
# GRAPHOS_XML_SENSOR_CALIBRATION_B2_TAG = "b2"
GRAPHOS_XML_SENSOR_CALIBRATION_K1_TAG = defs_opencv.OPENCV_CALIBRATION_K1_TAG
GRAPHOS_XML_SENSOR_CALIBRATION_K2_TAG = defs_opencv.OPENCV_CALIBRATION_K2_TAG
# GRAPHOS_XML_SENSOR_CALIBRATION_K3_TAG = "k3"
# GRAPHOS_XML_SENSOR_CALIBRATION_K4_TAG = "k4"
GRAPHOS_XML_SENSOR_CALIBRATION_P1_TAG = defs_opencv.OPENCV_CALIBRATION_P1_TAG
GRAPHOS_XML_SENSOR_CALIBRATION_P2_TAG = defs_opencv.OPENCV_CALIBRATION_P2_TAG
# GRAPHOS_XML_SENSOR_CALIBRATION_P3_TAG = "p3"
# GRAPHOS_XML_SENSOR_CALIBRATION_P4_TAG = "p4"

GRAPHOS_XML_IMAGES_TAG = "Images"
GRAPHOS_XML_IMAGES_IMAGE_TAG = "Image"
GRAPHOS_XML_IMAGES_IMAGE_ID_TAG = "@id"
GRAPHOS_XML_IMAGES_IMAGE_CAMERA_ID_TAG = "CameraId"
GRAPHOS_XML_IMAGES_IMAGE_CAMERA_POSITION_TAG = "CameraPosition"
GRAPHOS_XML_IMAGES_IMAGE_FILE_TAG = "File"

GRAPHOS_XML_ORIENTATIONS_TAG = "Orientations"
GRAPHOS_XML_ORIENTATIONS_CRS_TAG = "EnuCrs"
GRAPHOS_XML_ORIENTATIONS_REPORT_TAG = "Report"
GRAPHOS_XML_ORIENTATIONS_IMAGES_TAG = "Image"
GRAPHOS_XML_ORIENTATIONS_IMAGES_IMAGE_ID_TAG = "@image_id"
GRAPHOS_XML_ORIENTATIONS_IMAGES_IMAGE_ROT_TAG = "Rot"
GRAPHOS_XML_ORIENTATIONS_IMAGES_IMAGE_X_TAG = "X"
GRAPHOS_XML_ORIENTATIONS_IMAGES_IMAGE_Y_TAG = "Y"
GRAPHOS_XML_ORIENTATIONS_IMAGES_IMAGE_Z_TAG = "Z"

GRAPHOS_XML_GCPS_TAG = "GroundControlPoints"
GRAPHOS_XML_GCPS_CRS_TAG = "Crs"
GRAPHOS_XML_GCPS_GCP_TAG = "GroundControlPoint"
GRAPHOS_XML_GCPS_GCP_NAME_TAG = "Name"
GRAPHOS_XML_GCPS_GCP_X_TAG = "x"
GRAPHOS_XML_GCPS_GCP_Y_TAG = "y"
GRAPHOS_XML_GCPS_GCP_Z_TAG = "z"
GRAPHOS_XML_GCPS_GCP_ERROR_TAG = "error"
GRAPHOS_XML_GCPS_GCP_IMAGE_POINTS_TAG = "ImagePoints"
GRAPHOS_XML_GCPS_GCP_IMAGE_POINT_TAG = "ImagePoint"
GRAPHOS_XML_GCPS_GCP_IMAGE_POINT_TAG = "ImagePoint"
GRAPHOS_XML_GCPS_GCP_IMAGE_POINT_IMAGE_ID_TAG = "@image_id"
GRAPHOS_XML_GCPS_GCP_IMAGE_POINT_IMAGE_X_TAG = "x"
GRAPHOS_XML_GCPS_GCP_IMAGE_POINT_IMAGE_Y_TAG = "y"
GRAPHOS_XML_GCPS_GCP_IMAGE_POINT_IMAGE_ERROR_X_TAG = "ex"
GRAPHOS_XML_GCPS_GCP_IMAGE_POINT_IMAGE_ERROR_Y_TAG = "ey"


GRAPHOS_XML_MARKERS_MARKER_ATTRIBUTE_ID = "@id"
GRAPHOS_XML_MARKERS_MARKER_ATTRIBUTE_LABEL = "@label"




